### ISSUE TITLE
Wrong check on volumes

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc-health-checks#11]
The list of volumes mounted being checked is wrong. 
Please remove these and provide the minimum viable 

```
 * || check_fs_used /dev 90%
 * || check_fs_used / 90%
 * || check_fs_used /boot/efi 90%
 * || check_fs_used /mnt 90%
 * || check_fs_used /sched 90% => This doesn't exists
 * || check_fs_used /shared 90% => This doesn't exists
 * || check_fs_used /mnt/resource_nvme 90% => This doesn't exists

```

**Comment by rafsalas19** [comment]
@xpillons 
we are going to comment out the following:
```
 * || check_fs_used /sched 90% => This doesn't exists
 * || check_fs_used /shared 90% => This doesn't exists
 * || check_fs_used /mnt/resource_nvme 90% => This doesn't exists
```
can you elaborate on the correct volume percentages for the others?

@rajvi

**Comment by xpillons** [comment]
90% seems a good threshold
@rafsalas19  please check this https://github.com/Azure/azurehpc/tree/master/experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files
