### ISSUE TITLE
health check for NDv2 series?

### ISSUE THREAD

**Issue by ltalirz** [Azure/azurehpc-health-checks#54]
I've recently encountered cases of bad NDv2 nodes where running a pytorch code on one of the 8 GPUs would crash with a segfault but not on others.

I'm not sure whether the health checks in this repo would solve this, but perhaps it would still be useful to add a health check for the NDv2 family as well? @rafsalas19 

I've cobbled together the following check from a combination of `nc24s_v3.conf` and `nd96asr_v4.conf`, and it currently passes on an NDv2 nodes with `sudo nhc -c nd40rs_v2.conf -l ~/health.log -t 300` (I'm sure some adjustments are still required)

`nd40rs_v2.conf`
```
# NHC Configuration File
#
# Lines are in the form "<hostmask>||<check>"
# Hostmask is a glob, /regexp/, or {noderange}
# Comments begin with '#'
#
# This file was automatically generated by nhc-genconf
# Fri Nov 17 21:35:04 UTC 2023
#

#######################################################################
###
### NHC Configuration Variables
###
# * || export MARK_OFFLINE=1 NHC_CHECK_ALL=0


#######################################################################
###
### Hardware checks
###
 * || check_hw_cpuinfo 2 40 40
 * || check_hw_physmem 677258MB 677258MB 5%
 * || check_hw_swap 0kB 0kB 3%
 * || check_hw_ib 100 mlx5_ib0:1
 * || check_hw_eth ib0
 * || check_hw_eth lo
 * || check_hw_eth eth0


########################################################
####
#### GPU checks
####
# * || check_gpu_count 8
 * || check_gpu_xid
 * || check_nvsmi_healthmon
 * || check_gpu_clock_throttling
 * || check_cuda_bw 10
# * || check_gpu_ecc 20000000 10000
 * || check_gpu_clock_throttling

########################################################################
#####
##### Additional IB checks
#####
#* || check_ib_bw_gdr 100.0 nd40rs_v2
#* || check_nccl_allreduce_ib_loopback 18.0 1 /opt/microsoft/ndv4-topo.xml 16G
* || check_ib_link_flapping 6
```

**Comment by rafsalas19** [comment]
Hello @ltalirz,
The NDv2 checks are coming soon. Thanks for creating the conf file. I would expect them to be available by the next release which I am targeting the end of January.

It be interesting to know if the issue your encountering can be detected by the tests provided. If you can share that is.

**Comment by ltalirz** [comment]
Hey @rafsalas19 , thanks for following up!

> I would expect them to be available by the next release which I am targeting the end of January.

Great!

> It be interesting to know if the issue your encountering can be detected by the tests provided. 

No, unfortunately they do not detect the faulty GPU on our node.

You may notice that `check_gpu_ecc 20000000 10000` is still commented out - this is because I didn't know what the appropriate values were. If you can let me know, I may be able to run this check as well (will need to check whether we still have the "bad" node around).

I am still looking for a minimal way of detecting the GPU memory issue; looking at the `nvidia-smi` output showed no difference compared to GPUs that worked fine (including no elevated temperature).
If there are other, deeper test suites or more detailed reporting tools that we could run, please let me know!

**Comment by rafsalas19** [comment]
The latest release now supports the NDv2 SKU
