### ISSUE TITLE
Add an option to run-health-checks.sh to concatenate custom checks

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc-health-checks#66]
in azhop we have common custom checks on nodes in addition to the specific ones for the SKU.
For example we check that some NFS mount are mounted, some processes are running. The current `run-health-checks.sh` is great but doesn't allow customization of the configuration file dynamically built.

Check how this is done from here https://github.com/Azure/az-hop/blob/main/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/8-configure-nhc.sh

**Comment by rafsalas19** [comment]
Hello @xpillons,
Let me see if I have the correct understanding:

You want to dynamically add nhc tests when calling the run script. For instance, I have a conf file of common tests (ones not included by default).  I want them to be appended on the fly when I run ./run-health-checks.sh.
Basically, we want to pass an argument to the run script that points to existing conf file of common tests to be appended to the default.

Like line 31 of the example, you sent.

Is my understanding correct?

**Comment by xpillons** [comment]
@rafsalas19 yes this is exactly what I would like.

**Comment by rafsalas19** [comment]
@xpillons awesome, the work item has been created. I will update here when the feature is out.

**Comment by rafsalas19** [comment]
This feature has been checked in
