### ISSUE TITLE
install_stream is searching for /opt/AMD while it's /opt/amd

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc-health-checks#69]
hpc images are built with an install prefix of /opt/amd for all amd libraries. As a result the stream compilation will never use the amd clang tool 
https://github.com/Azure/azurehpc-health-checks/blob/main/customTests/custom-test-setup.sh#L72

**Comment by xpillons** [comment]
Oh in fact on the AlmaLinux 8.7 image there is a /opt/AMD folder with the compiler, this is really confusing.

**Comment by rafsalas19** [comment]
Hey, in azhpc images the clang compiler is set to be stored in /opt/AMD (if I remember correctly). I obviously can't remedy that in this repo. I can verify if this is the same on all images.

**Comment by xpillons** [comment]
yes that make sense, consistency in namings should be a best practice in the image repo, and can be solved by adding symlinks to provide compatibility in case of renaming. I'm closing this as it's not relevant in this repo.
